%{
Each scene N x 1 cell array containing obstacles. Each obstacle M x 2
vector of vertices making up the corners of the vertices. The vertices are
connected consecutively, such that the vertex at index k connects to vertex
k+1. The vertex at M connects back to 1. 
%}

standard_scene = {};

frame_width = 5;
frame = [0 0;...
    0 frame_width;...
    10 frame_width;...
    10 0];
standard_scene{end+1} = frame;
barrier_dx = 0.25;
barrier_gap_dy = 1;
barrier_1_x = 2.5;
barrier_1_gap_y = 3;
barrier_1_left = [barrier_1_x+barrier_dx/2, 0;...
    barrier_1_x+barrier_dx/2,barrier_1_gap_y-barrier_gap_dy/2;...
    barrier_1_x-barrier_dx/2, barrier_1_gap_y-barrier_gap_dy/2;...
    barrier_1_x-barrier_dx/2,0];
standard_scene{end+1} = barrier_1_left;

barrier_1_right = [barrier_1_x+barrier_dx/2, barrier_1_gap_y+barrier_gap_dy/2;...
    barrier_1_x+barrier_dx/2, frame_width;...
    barrier_1_x-barrier_dx/2, frame_width;...
    barrier_1_x-barrier_dx/2,barrier_1_gap_y+barrier_gap_dy/2];
standard_scene{end+1} = barrier_1_right;

barrier_2_x = 5;
barrier_2_gap_y = 1;
barrier_2_left = [barrier_2_x+barrier_dx/2, 0;...
    barrier_2_x+barrier_dx/2,barrier_2_gap_y-barrier_gap_dy/2;...
    barrier_2_x-barrier_dx/2, barrier_2_gap_y-barrier_gap_dy/2;...
    barrier_2_x-barrier_dx/2,0];
standard_scene{end+1} = barrier_2_left;

barrier_2_right = [barrier_2_x+barrier_dx/2, barrier_2_gap_y+barrier_gap_dy/2;...
    barrier_2_x+barrier_dx/2, frame_width;...
    barrier_2_x-barrier_dx/2, frame_width;...
    barrier_2_x-barrier_dx/2,barrier_2_gap_y+barrier_gap_dy/2];
standard_scene{end+1} = barrier_2_right;

barrier_3_x = 7.5;
barrier_3_gap_y = 4;
barrier_3_left = [barrier_3_x+barrier_dx/2, 0;...
    barrier_3_x+barrier_dx/2,barrier_3_gap_y-barrier_gap_dy/2;...
    barrier_3_x-barrier_dx/2, barrier_3_gap_y-barrier_gap_dy/2;...
    barrier_3_x-barrier_dx/2,0];
standard_scene{end+1} = barrier_3_left;

barrier_3_right = [barrier_3_x+barrier_dx/2, barrier_3_gap_y+barrier_gap_dy/2;...
    barrier_3_x+barrier_dx/2, frame_width;...
    barrier_3_x-barrier_dx/2, frame_width;...
    barrier_3_x-barrier_dx/2,barrier_3_gap_y+barrier_gap_dy/2];
standard_scene{end+1} = barrier_3_right;

save(fullfile(prj_path_list.scene_path,"standard_scene.mat"),"standard_scene","-mat");

clear barrier_1_gap_y barrier_2_left barrier_1_right barrier_1_x barrier_2_gap_y...
    barrier_2_left barrier_2_right barrier_2_x barrier_3_gap_y barrier_3_left...
    barrier_3_right barrier_3_x barrier_dx barrier_gap_dy fig frame frame_width
