function scene = createRandomScene()
%{
Each scene N x 1 cell array containing obstacles. Each obstacle M x 2
vector of vertices making up the corners of the vertices. The vertices are
connected consecutively, such that the vertex at index k connects to vertex
k+1. The vertex at M connects back to 1. 
%}

scene = {};

frame_width = 5;
frame = [0 0;...
    0 frame_width;...
    10 frame_width;...
    10 0];
scene{end+1} = frame;
barrier_dx = 0.25;
barrier_gap_dy = 1;
barrier_1_x = rand*1 + 2.5; %randomly move barriers up to 1 m forward or back from standard
barrier_1_gap_y = rand*(frame_width - barrier_gap_dy) + barrier_gap_dy/2; %randomly shift gap position
barrier_1_left = [barrier_1_x+barrier_dx/2, 0;...
    barrier_1_x+barrier_dx/2,barrier_1_gap_y-barrier_gap_dy/2;...
    barrier_1_x-barrier_dx/2, barrier_1_gap_y-barrier_gap_dy/2;...
    barrier_1_x-barrier_dx/2,0];
scene{end+1} = barrier_1_left;

barrier_1_right = [barrier_1_x+barrier_dx/2, barrier_1_gap_y+barrier_gap_dy/2;...
    barrier_1_x+barrier_dx/2, frame_width;...
    barrier_1_x-barrier_dx/2, frame_width;...
    barrier_1_x-barrier_dx/2,barrier_1_gap_y+barrier_gap_dy/2];
scene{end+1} = barrier_1_right;

barrier_2_x = rand*1 + 5;
barrier_2_gap_y = rand*(frame_width - barrier_gap_dy) + barrier_gap_dy/2;;
barrier_2_left = [barrier_2_x+barrier_dx/2, 0;...
    barrier_2_x+barrier_dx/2,barrier_2_gap_y-barrier_gap_dy/2;...
    barrier_2_x-barrier_dx/2, barrier_2_gap_y-barrier_gap_dy/2;...
    barrier_2_x-barrier_dx/2,0];
scene{end+1} = barrier_2_left;

barrier_2_right = [barrier_2_x+barrier_dx/2, barrier_2_gap_y+barrier_gap_dy/2;...
    barrier_2_x+barrier_dx/2, frame_width;...
    barrier_2_x-barrier_dx/2, frame_width;...
    barrier_2_x-barrier_dx/2,barrier_2_gap_y+barrier_gap_dy/2];
scene{end+1} = barrier_2_right;

barrier_3_x = rand*1 + 7.5;
barrier_3_gap_y = rand*(frame_width - barrier_gap_dy) + barrier_gap_dy/2;;
barrier_3_left = [barrier_3_x+barrier_dx/2, 0;...
    barrier_3_x+barrier_dx/2,barrier_3_gap_y-barrier_gap_dy/2;...
    barrier_3_x-barrier_dx/2, barrier_3_gap_y-barrier_gap_dy/2;...
    barrier_3_x-barrier_dx/2,0];
scene{end+1} = barrier_3_left;

barrier_3_right = [barrier_3_x+barrier_dx/2, barrier_3_gap_y+barrier_gap_dy/2;...
    barrier_3_x+barrier_dx/2, frame_width;...
    barrier_3_x-barrier_dx/2, frame_width;...
    barrier_3_x-barrier_dx/2,barrier_3_gap_y+barrier_gap_dy/2];
scene{end+1} = barrier_3_right;


clear barrier_1_gap_y barrier_2_left barrier_1_right barrier_1_x barrier_2_gap_y...
    barrier_2_left barrier_2_right barrier_2_x barrier_3_gap_y barrier_3_left...
    barrier_3_right barrier_3_x barrier_dx barrier_gap_dy fig frame frame_width

drawScene(figure(),scene)
end